[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Legacy redirects
[[redirects]]
  from = "/candidates"
  to = "/kandidaten/"
  status = 301

[[redirects]]
  from = "/companies"
  to = "/unternehmen/"
  status = 301

# SPA routing - serve the appropriate index.html for each route
[[redirects]]
  from = "/kandidaten/*"
  to = "/kandidaten/index.html"
  status = 200

[[redirects]]
  from = "/unternehmen/*"
  to = "/unternehmen/index.html"
  status = 200

[[redirects]]
  from = "/jobs/*"
  to = "/jobs/index.html"
  status = 200

[[redirects]]
  from = "/ueber-uns/*"
  to = "/ueber-uns/index.html"
  status = 200

[[redirects]]
  from = "/kontakt/*"
  to = "/kontakt/index.html"
  status = 200

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
